name: KasmWeb Brave with Ngrok

on: 
  workflow_dispatch:

jobs:
  run-brave:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker
      uses: actions/checkout@v3

    - name: Pull KasmWeb Brave Docker Image
      run: |
        docker pull kasmweb/brave:1.14.0 # Or the latest tag

    - name: Run KasmWeb Brave Container
      run: |
        docker run -d -p 6901:6901 -e VNC_PW=12341234 kasmweb/brave:1.14.0

    - name: Install Ngrok
      run: |
        sudo apt-get install -y jq
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt-get update && sudo apt-get install ngrok

    - name: Start Ngrok Tunnel for KasmWeb Brave
      run: |
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }} # Add your Ngrok authtoken to GitHub Secrets
        ngrok tcp 6901 & # Tunnel for Kasm's VNC port
        sleep 5
        curl -s http://localhost:4040/api/tunnels | jq '.tunnels[0].public_url'

    - name: Display Ngrok Public URL
      run: |
        echo "Access your KasmWeb Brave container at the following URL:"
        curl -s http://localhost:4040/api/tunnels | jq '.tunnels[0].public_url'
