# Reverse Windows RDP for GitHub Actions
# This YAML establishes the "build" workflow where we will execute all required scripts
# During the process, it should get stuck at the last step where it creates a new tunnel on ngrok.

name: MAC
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparing environment...
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install xRDP
      run: |
        brew install xrdp
        sudo brew services start xrdp

    - name: Set RDP Password
      run: |
        echo "username:password" | sudo chpasswd # Set your username and password
        sudo defaults write /Library/Preferences/com.apple.RemoteManagement VNCAlwaysStartOnLogin -bool true
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes -setvncpw -vncpw password # Set a VNC password
        
    - name: Start Ngrok Tunnel
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
      run: |
        brew install --cask ngrok
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }} # Add NGROK authtoken to GitHub Secrets
        ngrok tcp 5900 & # Tunnel for VNC/RDP

    - name: Retrieve Ngrok Public URL
      run: |
        sleep 10 # Allow ngrok to start
        curl -s http://localhost:4040/api/tunnels | jq '.tunnels[0].public_url'